version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

sphinx:
  configuration: docs/source/conf.py

# Set the version of Python and requirements required to build the docs.
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev