# # Configuration file for the Sphinx documentation builder.

# # -- Project information

# project = 'PyLips'
# copyright = '2024, Interaction Lab'
# author = 'Nathaniel Dennler'

# release = '0.1'
# version = '0.1.0'

# # -- General configuration

# extensions = [
#     'sphinx.ext.duration',
#     'sphinx.ext.doctest',
#     'sphinx.ext.autodoc',
#     'sphinx.ext.autosummary',
#     'sphinx.ext.intersphinx',
# ]

# intersphinx_mapping = {
#     'python': ('https://docs.python.org/3/', None),
#     'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
# }
# intersphinx_disabled_domains = ['std']

# templates_path = ['_templates']

# # -- Options for HTML output

# html_theme = 'sphinx_rtd_theme'

# # -- Options for EPUB output
# epub_show_urls = 'footnote'


# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.
import os
import sys

import sphinx_material

import pylips

sys.path.insert(0, os.path.abspath(".."))  # Detect ribs.
sys.path.append(os.path.abspath("./_ext"))  # Detect extensions.

DEV_MODE = os.environ.get("DOCS_MODE", "regular") == "dev"
READTHEDOCS_VERSION = os.environ.get("READTHEDOCS_VERSION", "stable")
READTHEDOCS_LANGUAGE = os.environ.get("READTHEDOCS_LANGUAGE", "en")

# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
needs_sphinx = "4.5.0"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named "sphinx.ext.*") or your custom ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx.ext.mathjax",
    "sphinx.ext.intersphinx",
    "sphinx_material",
    "sphinx_copybutton",
    "myst_nb",  # Covers both Markdown files and Jupyter notebooks.
    "sphinx_toolbox.more_autodoc.autonamedtuple",
    "sphinx_autodoc_typehints",
    "sphinx_codeautolink",
    # "github_links",
]

# Napoleon
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_use_param = True  # see tox-dev/sphinx-autodoc-typehints#15
napoleon_use_ivar = True
napoleon_include_special_with_doc = True

# MyST NB -- exclude execution of Jupyter notebooks because they can take a
# while to run.
nb_execution_mode = "off"

# https://github.com/executablebooks/MyST-NB/issues/441
myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_image",
]
# Auto-generate heading anchors.
myst_heading_anchors = 3

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = [".rst", ".md", ".ipynb"]

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "PyLips"
copyright = "2024, Interaction Lab"
author = "Nathaniel Dennler"

# The version info for the project you"re documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = pylips.__version__
# The full version, including alpha/beta/rc tags.
release = pylips.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
#  pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

github_repo_url = "https://github.com/interaction-lab/PyLips"

# -- Options for HTML output -------------------------------------------

html_show_sourcelink = True
html_sidebars = {"**": ["globaltoc.html", "localtoc.html", "searchbox.html"]}

html_theme_path = sphinx_material.html_theme_path()
html_context = sphinx_material.get_html_context()
html_theme = 'sphinx_rtd_theme'
html_logo = "_static/imgs/pylips_text.svg"
html_favicon = "_static/imgs/favicon.ico"
html_title = f"PyLips (v{version})"

#9e8da9

# # material theme options (see theme.conf for more information)
html_theme_options = {

}

html_static_path = ["_static"]

html_css_files = [
    "custom.css",
]

# # -- Extension config -------------------------------------------------

# Autodoc and autosummary
autodoc_member_order = "groupwise"  # Can be overridden by :member-order:
autodoc_default_options = {
    "inherited-members": True,
}
autosummary_generate = True


# Intersphinx
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
}